/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

def compat21 = JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_21)
def neoVersion = compat21 ? '2025.02.0' : '5.26.3'

dependencies {
    implementation "org.neo4j:neo4j:$neoVersion"
    implementation "org.apache.groovy:groovy:$groovyVersion"
    implementation 'org.neo4j:neo4j-graphql-java:1.9.1'
}

def runall = tasks.register('runAll') {
    group = 'Application'
}

FileUtil.baseNames(sourceSets.main.allSource.files).each { name ->
    def subtask = tasks.register("run$name", JavaExec) {
        dependsOn compileGroovy
        group = 'Application'
        description = "Run ${name}.groovy as a JVM application/Groovy script"
        classpath = sourceSets.main.runtimeClasspath
        mainClass = name
    }
    runall.configure {
        dependsOn subtask
    }
}
